### ISSUE TITLE
Accessing $1, $2 etc?

### ISSUE THREAD

**Issue by TheTechRobo** [AlphaShell-org/AlphaShell#2]
I mean in the root, i.e. before functions are run

**Comment by Maneren** [comment]
Good point, didn't think about that. I was mostly focused on using this for dotfiles or other sourced files, so I missed that fact that scripts have additional features. Gonna try adding that in the next version.

**Comment by Maneren** [comment]
Resolved in v0.4.0
You can now access arguments using `$0`, `$1`, etc. or `@` (array of arguments) similarly to zsh.
